[package]
name = "field-blockchain-data"
version = "0.1.0"
edition = "2021"

[dependencies]
sei-client={path = "../sei-client"}
serde = { version = "1.0", features = ["derive"] }
serde_json={version = "1.0.0"}